# Generated by Django 2.2.16 on 2020-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200914_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
