# Generated by Django 2.2.16 on 2020-09-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_cats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cats',
        ),
    ]
