# Generated by Django 2.2.16 on 2020-09-17 04:42

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200917_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
