# Generated by Django 2.2.16 on 2020-09-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200917_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
